version: "1.0"
services:
  web:
    build: ./server-main
    ports:
      - 8080:80
    volumes:
      - ./server-main:/usr/app
    env_file:
      - .env
    depends_on:
      - db
    command: air ./cmd/server/main.go -b 0.0.0.0

  db:
    build: ./server-main/migrations
    ports:
      - 5439:5432
    hostname: db
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  ai:
    build: ./server-ai
    ports:
      - 5000:5000
    volumes:
      - ./server-ai:/python-docker
    depends_on:
      - db
    env_file:
      - .env
    command: python3 -m flask --debug run --host=0.0.0.0
volumes:
  postgres-db:
