version: "1.0"
services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/usr/app
    env_file:
      - .env
    command: air ./cmd/server/main.go -b 0.0.0.0
  
  db:
    image: postgres:alpine
    ports:
      - 5431:5432
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes:
  postgres-db: