version: "1.0"
services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/usr/app
    env_file:
      - .env
    depends_on:
      - db
    command: air ./cmd/server/main.go -b 0.0.0.0
  
  db:
    build: ./migrations
    ports:
      - 5439:5432
    hostname: db
    volumes:
      # - ./migrations/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes:
  postgres-db: